name: master

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt,clippy
          rust-version: stable
      - uses: actions/checkout@v2
      - run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -D clippy::all

  test:
    needs: [lint]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test --all-targets --all-features
